### ISSUE TITLE
grid for discrete axis variables 

### ISSUE THREAD

**Issue by ivelsko** [nevrome/ggpointgrid#1]
I'd like to be able to use this for plots with discrete variables (such as the number of samples in each disease group (x-axis) that fit in each age group (y-axis)), but the points don't align and center with the variables. Would it be possible to make them do so?

**Comment by nevrome** [comment]
I think this issue was addressed with `ggpointgrid::geom_pointrect`, right?

**Comment by ivelsko** [comment]
Yep it was, thanks!

**Comment by nevrome** [comment]
:+1:
